version: '3'

services:
  nginx:
    image: torelog-ecs/nginx:latest 
    volumes:
      - ./docker/nginx/local/conf.d/default.conf:/etc/nginx/conf.d/default.conf 
    ports:
      - 8080:80
    expose:
      - 8080
    depends_on:
      - laravel
  laravel:
    image: torelog-ecs/laravel:latest
    volumes:
      - ./src:/application
    env_file:
      - ./src/.env
  db:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME:-homestead}
      - MYSQL_USER=${DB_USER:-homestead}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}
      - TZ=${TZ:-Asia/Tokyo}
    ports:
      - ${DB_PORT:-13306}:3306

volumes:
  db-store:    